### ISSUE TITLE
Option to specify custom allocators

### ISSUE THREAD

**Issue by legends2k** [ebassi/graphene#222]
`graphene_aligned_alloc` and `graphene_aligned_free` are used to allocate memory but it'd be beneficial to allow specifying alloc/dealloc functions for applications like games where custom memory allocators are commonplace to control memory usage patterns.  An option to override the alloc/free functions globally for the library would be useful.  Example: [stb](https://github.com/nothings/stb/blob/c9064e317699d2e495f36ba4f9ac037e88ee371a/stb_image.h#L648).

**Comment by ebassi** [comment]
Not a huge fan, to be honest.

The expected use of Graphene types is on the stack, or inlined inside structures; the heap allocation code is mostly there for integration with non-C users, consuming the Graphene API through bindings. That's why the whole `graphene_aligned_alloc()`/`graphene_aligned_free()` API is private.

Additionally, the alignment requirements are very strict; generic allocation code might very well end up breaking those constraints.

**Comment by legends2k** [comment]
> the heap allocation code is mostly there for integration with non-C users

Aah... then it's a non-issue for C or C++ programs which want to integrate it into their code's hot paths I guess.
