### ISSUE TITLE
X86 32bits builds fails

### ISSUE THREAD

**Issue by ndufresne** [ebassi/graphene#39]
We observe build failures on X86 32 bits platform. The problem is that to use SSE2 intrinsic, you need to enable SSE2 in compiler flags. Though, you don't want to do this globally, as we want to choose the right routine at run-time base on CPU flags.  The solution sens in pixman, is to split the SSE2 code into it's own .c and set flags for the compilation of that object only.

https://ci.gstreamer.net/view/All/job/cerbero-cross-mingw32/1755/console

Note it's very similar to issue #21 though it's a wider issue, as it affect iOS and Android builds too.

**Comment by ndufresne** [comment]
config.log
https://gist.github.com/ndufresne/e56fb3e14171148e840e

**Comment by ebassi** [comment]
I could use the Pixman approach, but the nice bit about the current code layout is that all the SIMD operations are either inlined or a C pre-processor define, which means that caller code gets the inlined version. Also unlike Pixman, the API exposed is public.

This looks more like a missing set of compiler flags in the `graphene-1.0.pc` file; right now, I added the compiler-specific flags as variables, but I think they will need to be added to the `Cflags` line.

**Comment by ndufresne** [comment]
Though would this mean we have to disable any SIMD if we want to support let's say X86 with and without SSE2 from the same build ?

**Comment by ebassi** [comment]
Well, internally something will have been compiled in the library, so you cannot really support both SSE2 and not support them in the same shared object.

**Comment by ebassi** [comment]
In order to support both at the same time, we'd have to make a smaller shared library with all the `graphene_simd4f_*` and `graphene_simd4x4f_*` symbols and `dlopen()` it depending on the architecture and other things. That would mean kissing all the inlining we do goodbye.

**Comment by ndufresne** [comment]
Normally we don't do that, instead we make sure to split .c (hence .o) so we can have different cflags. And at run time (through function pointer selected at init time usually, for speed reason), we pick the right routine.

**Comment by ebassi** [comment]
I honestly don't want to have the run time check for the CPU capabilities; building for 32 bit has become kind of an oddity, and it usually does not imply building a module once for both 32 bit and 64 bit architectures.

The performance impact of not inlining and, instead, going through a vtable for every single SIMD operation is not negligible, either. Pixman, for instance, gets away with it because it only has about a dozen functions dealing with SIMD types.

On a maintainership level, I also don't want to have to handle the complication of getting the CPU detection code inside Graphene, as well as the whole fallback code in place to degrade from SSE4.x to SSE3 to SSE2 to MMX.

For these reasons I'm closing this issue as 'wontfix'.

**Comment by ndufresne** [comment]
That may mean disabling SIMD on most distribution (or a least disabling some of it). It's not rare that the we use the same build for various SSE level support.
