### ISSUE TITLE
Explain a bit more the underlying maths?

### ISSUE THREAD

**Issue by swilmet** [ebassi/graphene#43]
I'm finally learning computer graphics with the Fundamentals of Computer Graphics book, by Shirley and Marshner. In parallel I'm looking at the graphene API and implementation.

I wonder if it makes sense to better explain the underlying maths in the graphene API. At least just a summary or examples.

For example for graphene_point_interpolate(), it could be explained that for a factor of 0 the result is the point a, for a factor of 1 it's the point b and 0.5 (for example) is at the middle of the line that goes through a and b.

Or is it considered too well-known to bother explaining that kind of thing?

**Comment by ebassi** [comment]
Usually, that's exactly what "linear interpolation" means, and I'd avoid adding that detail in every single `interpolate` function that is available in the API.

I'd gladly improve the documentation with examples and more explanation on the math and concepts, but for some of them I kind of assume people finding the library will have *some* prior knowledge.

**Comment by swilmet** [comment]
I have other examples of functions where explaining the conventions used would be useful, at least as a reminder:
- graphene_rect_union(): at first I didn't know what it does by just reading the API, and by reading the implementation I find it a bit strange.
- graphene_triangle_get_barycoords(): u and v are on which axes? ab and ac, respectively?
- graphene_triangle_get_midpoint(): explain where is the midpoint, exactly.

For interpolate(), 0 and 1 are just conventions. Maybe some old and less-well-known books use different conventions like -1 and 1 or whatever.

Anyway I think this is best discussed concretely on a case-by-case basis, I can come up with some patches.

But another potential audience for Graphene is for people learning computer graphics, as a nice complementary for a book explaining the theory (at least for the first chapters): see in practice how computer graphics data types are represented on the computer, implementing a basic ray-tracer, etc.

**Comment by ebassi** [comment]
Unioning rectangles is pretty much basic maths. The other two are more advanced, and I'd gladly review patches. Linking to Wikipedia is also allowed. :-)

Interpolation functions do not really have a defined range; I used a `double` because both `[ 0, 1 ]` or `[ -1, 2 ]` are fairly well understood and used ranges, but nothing prevents you from interpolating in the `[ -1, 1 ]` range with the same API, assuming you know which values you should expect. That's why the API reference does not say: "the interpolation factor, between X and Y" in the first place.

Another option worth exploring is to use the wiki or additional sections in the API reference for the basic concepts and conventions assumed throughout the library's API.

**Comment by ebassi** [comment]
I think we should close this issue, and instead open issues for the things that you think warrant more explanation.
