### ISSUE TITLE
matrix_unproject_point3d requires an inverted modelview matrix

### ISSUE THREAD

**Issue by ystreet** [ebassi/graphene#50]
To fully invert from screen space to model space, the modelview matrix passed to graphene_matrix_unproject_point3d needs to be inverted.  I believe that was attempted in e0c4e4c but reverted because it's a behaviour change by e0c4e4c5d.  Instead the documentation should be updated to mention that the caller needs to pass the inverted modelview matrix.

**Comment by ebassi** [comment]
Thanks for looking into this.

To be fair, I wanted to get back to commit e0c4e4c because I feel the current implementation is wrong, as it does not conform to `gluUnProject()`, which has been around enough to become "standard".

The only user is gthree, which is a bit of an academic exercise; so we may get away with "fixing" the behaviour of Graphene, and then update gthree. On the other hand, though, changing behaviours in a stable series is bad, so I'd be happy to go with a documentation update. After all, many libraries cache the inverse of the modelview to avoid incurring the cost of inverting wherever needed.

**Comment by ystreet** [comment]
Thanks!

I had attempted to use it instead of _find_model_coords() in http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/ext/gl/gstgltransformation.c#n497 however it was returning unexpected results ;)
