### ISSUE TITLE
Fix graphene_triangle_get_barycoords() for a point outside the triangle plane

### ISSUE THREAD

**Issue by swilmet** [ebassi/graphene#56]
`graphene_triangle_get_barycoords()` is based on [this algo](http://www.blackpawn.com/texts/pointinpoly/default.html). From the description on that page:

```
 With that in mind we can now describe any point on the plane as
    P = A + u * (C - A) + v * (B - A)
```

-> "on the plane".

From [the book](http://www.amazon.com/Fundamentals-Computer-Graphics-Peter-Shirley/dp/1568814690) that I read, there are three different algorithms described, with:
```
Although it is straightforward to solve Equation (2.32) algebraically, it is often fruitful to compute a direct geometric solution.
```

The algebraically equation being roughly the same as implemented in graphene currently.

One geometric solution is to compute the signed areas of the sub-triangles: `A_a` being the subtriangle PBC, `A_b` the subtriangle APC and `A_c` the subtriangle ABP, and `A` the area of the full triangle ABC. `A_a + A_b + A_c = A` if the point is in the same plane as the triangle. And the barycentric coordinates are `A_b/A` and `A_c/A`. Looks like a simple solution, at least on paper. (note that I've written this paragraph a bit quickly, it can contain some mistakes such as the order of the subtriangles vectors, since it matters for a signed area).

**Comment by ebassi** [comment]
I'm not really sure that we should "fix" anything. Also, not every solution ends up being computationally fast.

As far as I can see, barycentric coordinates are overwhelmingly used with coplanar points — i.e. they usually involve finding the normal of the triangle passing through the barycentre in order to compute the various directions in a mesh.

I'd rather have some benchmarks on how different solutions stack up than have a nominally "correct" solution to a larger problem space that is the one that is normally encountered.

**Comment by swilmet** [comment]
Yes, and verifying that a point belongs to the triangle plane can be done with other graphene functions. If nothing is done, it's better to document the restriction. And if later the restriction is lift, it won't be an API break.
